Домашнее задание 1
ZerSa/2018-FS-21-Frontend-Zendrikova pull request #1
Opened 2018-10-03 20:17 UTC by ZerSa

изменила функцию say

2018-10-03 22:05 UTC, martinkomitsky requested changes
Исправить замечания

2018-10-07 17:09 UTC, ZerSa commented
исправила замечания

2018-10-07 17:09 UTC, martinkomitsky approved these changes

2018-10-07 17:09 UTC, merged

2018-10-07 17:09 UTC, martinkomitsky commented
10